### ISSUE TITLE
Package fails to install using pip>=10

### ISSUE THREAD

**Issue by JirkaV** [wooyek/django-email-queue#4]
The package currently fails to install if pip is upgraded to version 10. Apparently it's a bad practice to use pip in setup.py. 

More in https://github.com/pypa/pip/issues/2286

**Comment by wooyek** [comment]
Yes it is, but I'm not a farmer I don't like to put requirements in `setup.py` by hand. This is a simple package and I could do it, but I'm lazy :) 

I have released new version.

**Comment by JirkaV** [comment]
Thanks! Any specific reason why the package requires Django>=2.0 and does not support LTS version?

**Comment by wooyek** [comment]
It should not require that if [python version is compatible with django](https://docs.djangoproject.com/en/dev/faq/install/#faq-python-version-support). 

I see now that there is somethig wrond with the [test matrix](https://travis-ci.org/wooyek/django-email-queue):

> py35-django-111 installed: apipkg==1.4,attrs==17.4.0,certifi==2018.4.16,chardet==3.0.4,coverage==4.5.1,**Django==2.0.4**,-e git+https://github.com/wooyek/django-email-queue.git@b44666680c36869a8e1eaa456bd85327a88d2b94#egg=django_email_queue, django-email-queue-example==0.15.0,django-environ==0.4.4,execnet==1.5.0,factory-boy==2.10.0,Faker==0.8.13,gunicorn==19.7.1,idna==2.6,mock==2.0.0,more-itertools==4.1.0,pbr==4.0.2,pluggy==0.6.0,psycopg2==2.7.4,py==1.5.3,pytest==3.5.0,pytest-cov==2.5.1,pytest-django==3.2.1,pytest-forked==0.2,pytest-html==1.17.0,pytest-metadata==1.7.0,pytest-sugar==0.9.1,pytest-xdist==1.22.2,python-coveralls==2.9.1,python-dateutil==2.7.2,pytz==2018.4,PyYAML==3.12,requests==2.18.4,six==1.11.0,termcolor==1.1.0,text-unidecode==1.2,urllib3==1.22,whitenoise==3.3.1

I will take a look, a that when I get some time.

**Comment by wooyek** [comment]
I have removed version constraints and just left `django>=1.8`. Hope this helps.

**Comment by JirkaV** [comment]
Helped tremendously, thanks for quick responses! Appreciate it!

**Comment by wooyek** [comment]
Happy to help. Happy that anyone is using this stuff :)
